"use client";

import { useState, useRef, useEffect } from "react";
import {
  X,
  Sparkles,
  Check,
  Loader2,
  AlertCircle,
  Send,
  Building,
  Info,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { approveHandover, HandoverRecord } from "@/lib/groupApi";
import { streamMessage } from "@/lib/api";
import Message, { Msg } from "./Message";

interface Props {
  handover: HandoverRecord | null;
  isOpen: boolean;
  onClose: () => void;
  onApproved: (updated: HandoverRecord) => void;
  currentUserId: string;
}

const INSURERS = [
  "Tata AIG Global Custom Guard",
  "Care Insurance Special Underwriting",
  "Digit Insurance Customized",
  "Star Health Premier Travel",
  "HDFC ERGO Travel Shield",
];

export default function HandoverApprovalModal({
  handover,
  isOpen,
  onClose,
  onApproved,
  currentUserId,
}: Props) {
  if (!isOpen || !handover) return null;

  const sessionId = handover.dm_session_id || `dm_handover_${handover.id}`;

  // Structured Policy Form State
  const [insurer, setInsurer] = useState(INSURERS[0]);
  const [planName, setPlanName] = useState("Custom Structured Travel Shield");
  const [premium, setPremium] = useState("₹3,950");
  const [sumInsured, setSumInsured] = useState("$100,000");
  const [destination, setDestination] = useState("International Travel");
  const [travelDates, setTravelDates] = useState("Custom Validity");
  const [riders, setRiders] = useState("Adventure Sports + Pre-existing Waiver");
  const [notes, setNotes] = useState("Special underwriter terms & discounts approved.");

  // Chat Consultation State
  const [chatMessages, setChatMessages] = useState<Msg[]>([]);
  const [inputText, setInputText] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [showContext, setShowContext] = useState(true);
  const [loadingApprove, setLoadingApprove] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const chatBottomRef = useRef<HTMLDivElement>(null);

  // Initialize initial briefing message on modal open
  useEffect(() => {
    if (!handover) return;
    const initialIntro: Msg = {
      role: "agent",
      text:
        `📋 **Custom Policy Handover Briefing**\n\n` +
        `**Client:** @${handover.requester_name} in *"${handover.group_name}"*\n\n` +
        `**Requirement & Group Context:**\n${handover.requirement}\n\n` +
        `Hey @${currentUserId}! How would you like to customize this policy for @${handover.requester_name}?\n` +
        `Tell me your requirements in natural language (e.g. *"Give 20% discount as diwali discount"*, *"Add extreme sports cover"*, *"Make price ₹1,500"*), ` +
        `and I will structure the plan for you!`,
    };
    setChatMessages([initialIntro]);
  }, [handover, currentUserId]);

  useEffect(() => {
    chatBottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages, isStreaming]);

  // Send instruction to Dolphin Buddy
  async function handleSendMessage(overrideText?: string) {
    const text = (overrideText || inputText).trim();
    if (!text || isStreaming) return;

    if (!overrideText) setInputText("");

    // Append user turn to modal chat
    setChatMessages((prev) => [...prev, { role: "user", text }]);
    setIsStreaming(true);
    setChatMessages((prev) => [...prev, { role: "agent", text: "" }]);

    const textToSend = `[HANDOVER CONSULTATION MODE | Client: @${handover?.requester_name} in "${handover?.group_name}" | Context & History:\n${handover?.requirement}]\n\n[Assigned Agent Instructions]: ${text}`;

    try {
      for await (const chunk of streamMessage(currentUserId, sessionId, textToSend)) {
        setChatMessages((prev) => {
          const updated = [...prev];
          const last = updated[updated.length - 1];
          if (last.role !== "agent") return prev;
          const newText = chunk.text ? last.text + chunk.text : last.text;

          // Auto-parse any POLICY_CARDS generated by Dolphin Buddy to update form fields
          const cardMatch = newText.match(/<!--POLICY_CARDS:([\s\S]*?)-->/);
          if (cardMatch) {
            try {
              const parsed = JSON.parse(cardMatch[1].trim());
              const card = Array.isArray(parsed) ? parsed[0] : parsed;
              if (card) {
                if (card.name) setPlanName(card.name);
                if (card.company) setInsurer(card.company);
                if (card.premium) {
                  const p = String(card.premium).replace(/[^0-9.]/g, "");
                  if (p) setPremium(`₹${Number(p).toLocaleString()}`);
                }
                if (card.sumInsured) setSumInsured(card.sumInsured);
                if (card.highlights && Array.isArray(card.highlights)) {
                  setRiders(card.highlights.join(" + "));
                }
              }
            } catch {}
          }

          return [
            ...updated.slice(0, -1),
            {
              role: "agent",
              text: newText,
              artifacts: chunk.artifacts ? [...(last.artifacts ?? []), ...chunk.artifacts] : last.artifacts,
            },
          ];
        });
      }
    } catch (err) {
      console.error("Consultation stream error:", err);
    } finally {
      setIsStreaming(false);
    }
  }

  async function handleApprove() {
    if (!handover) return;
    setLoadingApprove(true);
    setError(null);
    try {
      const resolutionData = {
        insurer,
        plan_name: planName,
        premium,
        sum_insured: sumInsured,
        destination,
        travel_dates: travelDates,
        riders,
        notes,
      };

      const updated = await approveHandover(handover.id, currentUserId, resolutionData);
      onApproved(updated);
      onClose();
    } catch (err: any) {
      setError(err?.message || "Failed to approve handover");
    } finally {
      setLoadingApprove(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-2 sm:p-4 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl h-[90vh] max-h-[850px] overflow-hidden border border-gray-200 flex flex-col">
        {/* Top Header */}
        <div className="bg-[#1e293b] px-4 sm:px-6 py-3.5 text-white flex items-center justify-between shrink-0 shadow-xs">
          <div className="flex items-center gap-2.5 min-w-0">
            <div className="w-8 h-8 rounded-full bg-[#ff5722] flex items-center justify-center text-white shrink-0">
              <Sparkles size={16} />
            </div>
            <div className="truncate">
              <h2 className="font-bold text-sm truncate flex items-center gap-2">
                <span>Handover Consultation: Custom Policy Structuring</span>
                <span className="text-[10px] bg-amber-500 text-black px-1.5 py-0.2 rounded-full font-black uppercase">
                  Live AI Underwriter
                </span>
              </h2>
              <p className="text-[11px] text-gray-300 truncate">
                Group: <span className="font-semibold text-white">{handover.group_name}</span> · Client: @{handover.requester_name}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-full hover:bg-white/10 text-gray-300 hover:text-white transition-colors cursor-pointer ml-2"
          >
            <X size={19} />
          </button>
        </div>

        {/* Main 2-Column Body: Chat Consultation (Left) + Structured Plan Summary (Right) */}
        <div className="flex-1 min-h-0 flex flex-col md:flex-row divide-y md:divide-y-0 md:divide-x divide-gray-200 bg-[#f8fafc]">
          
          {/* Left / Main Column: Live AI Chat */}
          <div className="flex-1 flex flex-col min-w-0 h-full bg-[#efeae2] relative">
            
            {/* Collapsible Group Context Banner */}
            <div className="bg-amber-50 border-b border-amber-200 text-amber-900 text-xs px-3 py-2 shrink-0">
              <div
                onClick={() => setShowContext(!showContext)}
                className="flex items-center justify-between cursor-pointer font-bold select-none"
              >
                <span className="flex items-center gap-1.5">
                  <Info size={14} className="text-amber-700" />
                  Client Requirement & Context from &quot;{handover.group_name}&quot;
                </span>
                {showContext ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </div>
              {showContext && (
                <div className="mt-1.5 p-2 bg-white/80 rounded-lg border border-amber-200/60 text-[11px] max-h-24 overflow-y-auto whitespace-pre-line text-gray-800">
                  {handover.requirement}
                </div>
              )}
            </div>

            {/* Chat Thread */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3">
              {chatMessages.map((m, idx) => (
                <Message
                  key={idx}
                  msg={m}
                  userId={currentUserId}
                  sessionId={sessionId}
                  isSelf={m.role === "user"}
                  senderLabel={m.role === "agent" ? "Dolphin Buddy" : currentUserId}
                  onSend={(t) => handleSendMessage(t)}
                />
              ))}
              <div ref={chatBottomRef} />
            </div>

            {/* Input Dock */}
            <div className="p-2.5 bg-[#f0f2f5] border-t border-[#e9edef] flex items-center gap-2">
              <input
                type="text"
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleSendMessage();
                  }
                }}
                placeholder="Instruct Dolphin Buddy (e.g. 'Give 20% discount as diwali discount')..."
                className="flex-1 px-3.5 py-2 bg-white rounded-xl text-xs border border-gray-300 focus:outline-hidden focus:ring-1 focus:ring-[#008069] text-[#111b21]"
              />
              <button
                onClick={() => handleSendMessage()}
                disabled={!inputText.trim() || isStreaming}
                className="p-2 bg-[#008069] hover:bg-[#006e5a] disabled:opacity-50 text-white rounded-xl transition-colors cursor-pointer shrink-0 shadow-2xs"
                title="Send command"
              >
                {isStreaming ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}
              </button>
            </div>
          </div>

          {/* Right Column: Live Structured Plan Summary & Approval Form */}
          <div className="w-full md:w-80 lg:w-96 p-4 bg-white flex flex-col overflow-y-auto text-xs shrink-0">
            <div className="mb-3">
              <h3 className="font-bold text-gray-900 text-sm flex items-center gap-1.5">
                <Building size={16} className="text-[#008069]" /> Structured Plan Summary
              </h3>
              <p className="text-[11px] text-gray-500">
                Values auto-sync from your AI chat. You can also edit directly before publishing.
              </p>
            </div>

            {error && (
              <div className="mb-3 p-2 bg-red-50 border border-red-200 rounded-lg text-red-600 font-medium flex items-center gap-1.5 text-[11px]">
                <AlertCircle size={13} />
                <span>{error}</span>
              </div>
            )}

            <div className="space-y-2.5 flex-1">
              <div>
                <label className="block text-[10px] font-bold text-gray-600 uppercase mb-0.5">
                  Plan Name
                </label>
                <input
                  type="text"
                  value={planName}
                  onChange={(e) => setPlanName(e.target.value)}
                  className="w-full px-2.5 py-1.5 bg-[#f0f2f5] rounded-lg font-semibold text-gray-900 text-xs border border-transparent focus:border-[#008069] focus:outline-hidden"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-600 uppercase mb-0.5">
                  Underwriter / Insurer
                </label>
                <input
                  type="text"
                  value={insurer}
                  onChange={(e) => setInsurer(e.target.value)}
                  className="w-full px-2.5 py-1.5 bg-[#f0f2f5] rounded-lg font-semibold text-gray-900 text-xs border border-transparent focus:border-[#008069] focus:outline-hidden"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-[10px] font-bold text-gray-600 uppercase mb-0.5">
                    Premium (₹)
                  </label>
                  <input
                    type="text"
                    value={premium}
                    onChange={(e) => setPremium(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-[#f0f2f5] rounded-lg font-black text-[#15803d] text-xs border border-transparent focus:border-[#008069] focus:outline-hidden"
                  />
                </div>
                <div>
                  <label className="block text-[10px] font-bold text-gray-600 uppercase mb-0.5">
                    Sum Insured
                  </label>
                  <input
                    type="text"
                    value={sumInsured}
                    onChange={(e) => setSumInsured(e.target.value)}
                    className="w-full px-2.5 py-1.5 bg-[#f0f2f5] rounded-lg font-semibold text-gray-900 text-xs border border-transparent focus:border-[#008069] focus:outline-hidden"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-600 uppercase mb-0.5">
                  Special Riders / Add-ons
                </label>
                <textarea
                  rows={2}
                  value={riders}
                  onChange={(e) => setRiders(e.target.value)}
                  className="w-full px-2.5 py-1.5 bg-[#f0f2f5] rounded-lg font-medium text-gray-900 text-xs border border-transparent focus:border-[#008069] focus:outline-hidden resize-none"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-gray-600 uppercase mb-0.5">
                  Approval Notes
                </label>
                <textarea
                  rows={2}
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  className="w-full px-2.5 py-1.5 bg-[#f0f2f5] rounded-lg font-medium text-gray-900 text-xs border border-transparent focus:border-[#008069] focus:outline-hidden resize-none"
                />
              </div>
            </div>

            {/* Bottom Action Button */}
            <div className="pt-3 mt-3 border-t border-gray-200 flex flex-col gap-2">
              <button
                onClick={handleApprove}
                disabled={loadingApprove}
                className="w-full py-2.5 px-4 bg-[#008069] hover:bg-[#006e5a] disabled:opacity-50 text-white font-bold text-xs rounded-xl shadow-xs transition-all flex items-center justify-center gap-1.5 cursor-pointer"
              >
                {loadingApprove ? (
                  <>
                    <Loader2 size={14} className="animate-spin" /> Publishing to Group...
                  </>
                ) : (
                  <>
                    <Check size={15} /> Approve & Post to &quot;{handover.group_name}&quot;
                  </>
                )}
              </button>
              <button
                onClick={onClose}
                className="w-full py-1.5 text-xs text-gray-500 hover:text-gray-800 font-medium transition-colors text-center cursor-pointer"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

