// All requests go through Next.js rewrite proxy → avoids CORS
const BASE_URL = "/api/backend";
const APP_NAME = "my_agent";

export { BASE_URL, APP_NAME };

export async function createSession(userId: string, sessionId: string) {
  const res = await fetch(
    `${BASE_URL}/apps/${APP_NAME}/users/${userId}/sessions/${sessionId}`,
    { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }
  );
  // 409 = session already exists, which is fine — just reuse it
  if (!res.ok && res.status !== 409) throw new Error("Failed to create session");
  return res.status === 409 ? { reused: true } : res.json();
}

export function buildDownloadUrl(userId: string, sessionId: string, filename: string) {
  // Always use the proxied path so it works when served through Next.js
  return `${BASE_URL}/download/${APP_NAME}/${userId}/${sessionId}/${filename}`;
}

/** Absolute backend download URL — resolves correctly regardless of frontend origin */
export function buildAbsoluteDownloadUrl(userId: string, sessionId: string, filename: string) {
  const backendBase = process.env.NEXT_PUBLIC_API_URL || "http://43.204.143.233:8000";
  return `${backendBase}/download/${APP_NAME}/${userId}/${sessionId}/${filename}`;
}

// Direct EC2 URL for cases where proxy streaming might buffer (fallback)
export const DIRECT_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://43.204.143.233:8000";

export interface ChatMessage {
  role: "user" | "agent";
  text: string;
  artifacts?: string[]; // filenames
  userAttachment?: { name: string; mimeType: string; data?: string };
}

// ── Session list & history ────────────────────────────────────────────────────
export interface SessionSummary {
  id: string;
  lastUpdateTime: number;
  preview: string; // first user message text
}

export interface ADKEvent {
  id: string;
  author: string;
  content?: { role: string; parts: { text?: string }[] };
  actions?: { artifactDelta?: Record<string, number> };
  timestamp: number;
}

export interface WalletInfo {
  user_id: string;
  balance: number;
  updated_at: string;
}

export async function fetchWallet(userId: string): Promise<WalletInfo> {
  const res = await fetch(`${BASE_URL}/wallet/${userId}`);
  if (!res.ok) return { user_id: userId, balance: 0, updated_at: "" };
  return res.json();
}

export async function updateWallet(userId: string, balance: number): Promise<WalletInfo> {
  const res = await fetch(`${BASE_URL}/wallet/${userId}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ balance }),
  });
  if (!res.ok) throw new Error("Failed to update wallet balance");
  return res.json();
}

export async function topupWallet(userId: string, amount: number): Promise<WalletInfo> {
  const res = await fetch(`${BASE_URL}/wallet/${userId}/topup`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ amount }),
  });
  if (!res.ok) throw new Error("Failed to top up wallet balance");
  return res.json();
}

export interface ADKSession {
  id: string;
  appName: string;
  userId: string;
  state: Record<string, unknown>;
  events: ADKEvent[];
  lastUpdateTime: number;
}

export async function listSessions(userId: string): Promise<ADKSession[]> {
  const res = await fetch(`${BASE_URL}/apps/${APP_NAME}/users/${userId}/sessions`);
  if (!res.ok) return [];
  const data = await res.json();
  // ADK returns either an array directly or { sessions: [...] }
  return Array.isArray(data) ? data : (data.sessions ?? []);
}

export async function getSession(userId: string, sessionId: string): Promise<ADKSession | null> {
  const res = await fetch(`${BASE_URL}/apps/${APP_NAME}/users/${userId}/sessions/${sessionId}`);
  if (!res.ok) return null;
  return res.json();
}

export async function deleteSession(userId: string, sessionId: string): Promise<void> {
  await fetch(`${BASE_URL}/apps/${APP_NAME}/users/${userId}/sessions/${sessionId}`, { method: "DELETE" });
}

export async function uploadArtifact(
  userId: string,
  sessionId: string,
  filename: string,
  mimeType: string,
  data: string
): Promise<{ status: string; filename: string; version?: number }> {
  const res = await fetch(`${BASE_URL}/upload-artifact`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      app_name: APP_NAME,
      user_id: userId,
      session_id: sessionId,
      filename,
      mime_type: mimeType,
      data,
    }),
  });
  if (!res.ok) throw new Error("Failed to upload artifact");
  return res.json();
}

/** Helper to verify if an artifact was generated by the agent vs uploaded by user */
export function isAgentGeneratedArtifact(filename: string): boolean {
  if (!filename) return false;
  const lower = filename.toLowerCase();
  return (
    lower.startsWith("booking_confirmation_") ||
    lower.startsWith("quotation_comparison_") ||
    lower.endsWith("_insurance_guide.pdf") ||
    lower.endsWith("_guide.pdf") ||
    lower.endsWith("_summary.pdf")
  );
}

/** Extract readable messages from ADK session events */
export function eventsToMessages(events: ADKEvent[]): ChatMessage[] {
  const msgs: ChatMessage[] = [];
  // Collect pending artifacts from tool-result events to attach to the NEXT agent message
  const pendingArtifacts: string[] = [];

  for (const ev of events) {
    const artifactDelta = ev.actions?.artifactDelta;
    if (artifactDelta && Object.keys(artifactDelta).length > 0) {
      const generated = Object.keys(artifactDelta).filter(isAgentGeneratedArtifact);
      if (generated.length > 0) pendingArtifacts.push(...generated);
    }

    const parts = ev.content?.parts;
    const text = parts?.find((p: Record<string, unknown>) => typeof p.text === "string")?.text as string | undefined;

    if (ev.content?.role === "user") {
      // Skip tool/function response events — they aren't real user messages
      const isFunctionResponse = parts?.some((p: Record<string, unknown>) => "functionResponse" in p);
      if (!isFunctionResponse) {
        // Check for inlineData in parts
        const inlinePart = parts?.find(
          (p: Record<string, unknown>) => "inlineData" in p || "inline_data" in p
        ) as Record<string, { mimeType?: string; mime_type?: string; data?: string }> | undefined;
        const inlineObj = inlinePart?.inlineData || inlinePart?.inline_data;

        // Extract attachment name from the 📎 marker if present in text
        const attachMatch = text ? text.match(/\n?📎 (.+)$/) : null;
        let userAttachment: { name: string; mimeType: string; data?: string } | undefined = undefined;

        if (attachMatch) {
          const name = attachMatch[1].trim();
          const ext = name.split(".").pop()?.toLowerCase() || "";
          let mimeType = inlineObj?.mimeType || inlineObj?.mime_type || "application/octet-stream";
          if (mimeType === "application/octet-stream") {
            if (["png", "jpg", "jpeg", "webp", "gif", "bmp"].includes(ext)) {
              mimeType = `image/${ext === "jpg" ? "jpeg" : ext}`;
            } else if (ext === "pdf") {
              mimeType = "application/pdf";
            }
          }
          userAttachment = { name, mimeType, data: inlineObj?.data };
        } else if (inlineObj) {
          const mimeType = inlineObj.mimeType || inlineObj.mime_type || "application/octet-stream";
          const isImage = mimeType.startsWith("image/");
          const name = isImage ? "image.png" : "document.pdf";
          userAttachment = { name, mimeType, data: inlineObj.data };
        }

        const msgText = text || (userAttachment ? `📎 ${userAttachment.name}` : "");
        if (msgText || userAttachment) {
          msgs.push({ role: "user", text: msgText, userAttachment });
        }
      }
    } else if (ev.content?.role === "model" && text) {
      // Flush any pending artifacts onto this agent message
      const artifacts = pendingArtifacts.length > 0 ? [...pendingArtifacts] : undefined;
      pendingArtifacts.length = 0; // clear

      const last = msgs[msgs.length - 1];
      if (last?.role === "agent") {
        // Deduplicate: don't append if this text is already contained in the agent message
        const isDuplicate = last.text.includes(text.trim()) && text.trim().length > 40;
        if (!isDuplicate) {
          last.text += text;
        }
        if (artifacts) last.artifacts = [...(last.artifacts ?? []), ...artifacts];
      } else {
        msgs.push({ role: "agent", text, artifacts });
      }
    }
  }

  // If there are still pending artifacts after all events (edge case),
  // attach to the last agent message
  if (pendingArtifacts.length > 0) {
    const lastAgent = [...msgs].reverse().find((m) => m.role === "agent");
    if (lastAgent) {
      lastAgent.artifacts = [...(lastAgent.artifacts ?? []), ...pendingArtifacts];
    }
  }

  return msgs;
}

/** Get first user message as a preview title */
export function sessionPreview(events: ADKEvent[]): string {
  for (const ev of events) {
    if (ev.content?.role === "user") {
      // Skip tool/function response events
      const isFunctionResponse = ev.content.parts?.some((p: Record<string, unknown>) => p.functionResponse);
      if (isFunctionResponse) continue;
      const text = ev.content.parts?.find((p) => p.text)?.text;
      if (text) {
        const clean = text.replace(/\n?📎 .+$/, "").trim();
        return (clean || "Conversation").slice(0, 60) + (clean.length > 60 ? "…" : "");
      }
    }
  }
  return "New conversation";
}
// ─────────────────────────────────────────────────────────────────────────────

// ── Dynamic data API ──────────────────────────────────────────────────────────
export type DataKey = "faqs" | "claims" | "premium_config" | "response_prompt" | "addons" | "vas";

export async function fetchData(key: DataKey): Promise<Record<string, unknown>> {
  const res = await fetch(`${BASE_URL}/data/${key}`);
  if (!res.ok) throw new Error(`Failed to load ${key}`);
  return res.json();
}

export async function saveData(key: DataKey, data: Record<string, unknown>): Promise<void> {
  const res = await fetch(`${BASE_URL}/data/${key}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error(`Failed to save ${key}`);
}
// ─────────────────────────────────────────────────────────────────────────────

// ── Bookings API ──────────────────────────────────────────────────────────────
export interface Booking {
  ref_number: string;
  created_at: string;
  updated_at: string;
  user_id: string;
  session_id: string;
  policy_name: string;
  insurer: string;
  destination: string;
  travel_dates: string;
  num_adults: number;
  num_children: number;
  traveller_ages: string;
  sum_insured: string;
  premium: string;
  artifact_ids: string[];
  addons: Array<{ key: string; name: string; cost?: number } | string>;
  status: string;
  notes: string;
}

export async function fetchBookings(userId?: string): Promise<Booking[]> {
  const url = userId ? `${BASE_URL}/bookings?user_id=${userId}` : `${BASE_URL}/bookings`;
  const res = await fetch(url);
  if (!res.ok) throw new Error("Failed to load bookings");
  const data = await res.json();
  return data.bookings ?? [];
}

export async function fetchBooking(refNumber: string): Promise<Booking | null> {
  const res = await fetch(`${BASE_URL}/bookings/${refNumber}`);
  if (!res.ok) return null;
  return res.json();
}

export async function updateBooking(
  refNumber: string,
  updates: Partial<Pick<Booking, "policy_name" | "insurer" | "destination" | "travel_dates" | "num_adults" | "num_children" | "traveller_ages" | "sum_insured" | "premium" | "notes">>
): Promise<Booking> {
  const res = await fetch(`${BASE_URL}/bookings/${refNumber}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });
  if (!res.ok) throw new Error("Failed to update booking");
  return res.json();
}

export async function cancelBooking(refNumber: string): Promise<void> {
  const res = await fetch(`${BASE_URL}/bookings/${refNumber}`, { method: "DELETE" });
  if (!res.ok) throw new Error("Failed to cancel booking");
}

/** Build the best download URL for a booking artifact.
 *  If session_id is missing, falls back to the session-agnostic endpoint. */
export function buildBookingDownloadUrl(userId: string, sessionId: string, filename: string): string {
  if (sessionId) {
    return `${BASE_URL}/download/${APP_NAME}/${userId}/${sessionId}/${filename}`;
  }
  // session_id not stored — use the scan-all-sessions fallback endpoint
  return `${BASE_URL}/download-artifact/${APP_NAME}/${userId}/${filename}`;
}
// ─────────────────────────────────────────────────────────────────────────────

export async function* streamMessage(
  userId: string,
  sessionId: string,
  text: string,
  inlineData?: { mimeType: string; data: string }
): AsyncGenerator<{ text?: string; artifacts?: string[] }> {
  const parts: object[] = [{ text }];
  if (inlineData) parts.push({ inlineData });

  const res = await fetch(`${BASE_URL}/run_sse`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      appName: APP_NAME,
      userId,
      sessionId,
      newMessage: { role: "user", parts },
      streaming: true,
    }),
  });

  if (!res.ok || !res.body) throw new Error("SSE request failed");

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  // Track accumulated text to deduplicate repeated agent turns
  let accumulatedText = "";

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";

    for (const line of lines) {
      if (!line.startsWith("data:")) continue;
      const raw = line.slice(5).trim();
      if (!raw || raw === "[DONE]") continue;
      try {
        const event = JSON.parse(raw);

        // Collect agent-generated artifacts from ANY event that carries artifactDelta
        const artifactDelta = event?.actions?.artifactDelta;
        const rawArtifacts = artifactDelta && Object.keys(artifactDelta).length > 0
          ? Object.keys(artifactDelta).filter(isAgentGeneratedArtifact)
          : [];
        const artifacts = rawArtifacts.length > 0 ? rawArtifacts : undefined;

        // Only pull text from model-role content parts
        const content = event?.content;
        const isModelContent = content?.role === "model";
        const textPart = isModelContent
          ? content.parts?.find((p: { text?: string }) => p.text)?.text
          : undefined;

        if (textPart) {
          // Deduplicate: if the agent emits the same text again in a second turn, skip it
          if (accumulatedText.includes(textPart.trim()) && textPart.trim().length > 40) {
            continue;
          }
          accumulatedText += textPart;
        }

        if (textPart || artifacts) yield { text: textPart, artifacts };
      } catch {
        // skip malformed chunks
      }
    }
  }
}

// ── Dashboard Analytics Data ──────────────────────────────────────────────────
export interface DashboardStats {
  summary: {
    total_bookings: number;
    active_policies: number;
    pending_policies: number;
    cancelled_policies: number;
    total_premium_inr: number;
    avg_premium_inr: number;
    policy_ratio: string;
    wallet_balance: number;
    partner_count: number;
    active_agents: number;
  };
  claims_verification: {
    accuracy_percentage: number;
    instant_approved: number;
    under_review: number;
    settlement_ratio: string;
  };
  insurer_distribution: {
    name: string;
    count: number;
    percentage: number;
    color: string;
  }[];
  destination_distribution: {
    category: string;
    count: number;
    percentage: number;
    color: string;
  }[];
  recent_activities: {
    ref_number: string;
    created_at: string;
    policy_name: string;
    insurer: string;
    destination: string;
    travel_dates: string;
    num_adults: number;
    num_children: number;
    sum_insured: string;
    premium: string;
    status: string;
  }[];
}

export async function fetchDashboardStats(userId?: string): Promise<DashboardStats> {
  const url = userId ? `${BASE_URL}/dashboard/stats?user_id=${userId}` : `${BASE_URL}/dashboard/stats`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error("Failed to fetch dashboard statistics");
  }
  return res.json();
}
